# Generated by Django 5.0.3 on 2024-04-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_persons_alter_menu_inventory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_date_constraint',
        ),
    ]
